language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10

services:
  - memcached
  - redis
  - rabbitmq

addons:
  postgresql: "9.4"

bundler_args: --without test --jobs 3 --retry 3

before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "[ -f /tmp/beanstalkd-1.10/Makefile ] || (curl -L https://github.com/kr/beanstalkd/archive/v1.10.tar.gz | tar xz -C /tmp)"
  - "pushd /tmp/beanstalkd-1.10 && make && (./beanstalkd &); popd"

before_script:
  - bundle update

script: 'ci/travis.rb'

env:
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=ac"
    - "GEM=ac FAYE=1"
    - "GEM=am,amo,as,av,aj"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
    - "GEM=guides"

rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head

matrix:
  include:
    # Latest compiled version in http://rubies.travis-ci.org
    - rvm: 2.3.0
      env:
        - "GEM=ar:mysql2"
      addons:
        mariadb: 10.0
    - rvm: jruby-9.0.5.0
      jdk: oraclejdk8
      env:
        - "JRUBY_OPTS='--dev -J-Xmx1024M'"
        - "GEM='ap'"
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
  fast_finish: true

